### ISSUE TITLE
Ajouter les flèches de trie sur les colones

### ISSUE THREAD

**Issue by mbreton** [js-republic/banner-handler#2]
Le trie étant déjà implémenté sur les colonnes de début et de fin. Il faut juste ajouter des flèches et gérer leur direction en fonction de si le trie est ascendant ou descendant.

**Comment by sylvan0s** [comment]
Pull request #14 has been made to handle this issue.

**Comment by sylvan0s** [comment]
The pull request #14 has been approved and merged.
