### ISSUE TITLE
Voir compte authentifié en haut à droite

### ISSUE THREAD

**Issue by mbreton** [js-republic/banner-handler#4]
J'aimerais en tant qu'utilisateur voir mon nom ainsi que mon avatar affiché en haut à droite dans la barre d'outils quand je suis connecté.

Test d'acceptance :
- Je me rend sur `/login`
- Je me connecte via Google (et accepte le cas échéant l'autorisation Google)
- J'arrive sur `/main`
- Je dois voir en haut à droite mon avatar en forme ronde avec mon nom écrit à sa droite

Note technique :
Une route `auth/user` renvoie déjà les informations de l'utilisateur actuel, et est invoquée par le *AuthGuard* grâce au service *AuthService* à chaque tentative de se rendre sur `/main`. Il faut donc partager l'information récupérée par ce service pour la rendre accessible au composant qui gère la toolbar.

**Comment by guillaumebarranco** [comment]
Pull request https://github.com/js-republic/banner-handler/pull/10 has been made to handle this issue.

**Comment by sylvan0s** [comment]
Pull request #10 has been approved.
